# Generated by Django 3.1.7 on 2021-03-13 15:26

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('Scheduled', 'Scheduled'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default=('Scheduled', 'Scheduled'), max_length=50)),
                ('time', models.DateTimeField()),
                ('url', models.URLField(max_length=1200)),
            ],
        ),
    ]
