# Generated by Django 3.1.7 on 2021-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(default='Schdeuled', max_length=20),
        ),
    ]
