# Generated by Django 3.1.7 on 2021-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(max_length=1200, null=True),
        ),
    ]
