# Generated by Django 3.1.7 on 2021-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20210618_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, max_length=1200, null=True),
        ),
    ]
