# Generated by Django 3.1.7 on 2021-06-18 14:21

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20210618_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=task.models.upload_location),
        ),
    ]
