# Generated by Django 3.1.7 on 2021-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20210618_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
